
import { abril, cormorant, dancingScript, playfair, quicksand } from "@/lib/fonts";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import clsx from 'clsx'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(abril.variable, cormorant.variable, dancingScript.variable, 'font-sans')}>
        {children}
      </body>
    </html>
  )
}
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${abril.variable} ${cormorant.variable} ${dancingScript.variable}`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
